version: 2
jobs:
  build:
    docker:
      - image: springcloud/pipeline-base
    environment:
      _JAVA_OPTIONS: "-Xms1024m -Xmx2048m"
      TERM: dumb
    branches:
      ignore:
        - gh-pages # list of branches to ignore
    resource_class: large
    steps:
      - checkout
      - run:
          name: "Running build"
          command: ./gradlew clean build
